Solution to part  5:Python Exceptions

